### ISSUE TITLE
Add "record" datatype

### ISSUE THREAD

**Issue by antagonist112358** [rsdn/nemerle#13278]
I'd like to propose adding a new datatype to nemerle - the "record" type, and the corresponding keyword - "record" to represent this type.

<h2>Justification:</h2>
Extend the [Record] attribute macro into a full language feature. Further, unlike classes marked with the [Record] attribute, records do not allow for any class features to be defined. Only the required constructor signature is allowed.

These types are used only to store data, as per the definition of a record type.

Records are either converted into classes of the same name or structs during the compile phase.

<h2>Syntax:</h2>
_Simple record_
record UserEntry(name: string, username: string, password_hash: long)

_Records allow for access modifiers (same as classes)_
(public|private|internal) record Album(artist: string, tracks: list[track])

_Records allow for inheritance - which simply adds additional fields to the record_
public record Employee(id: int, name: string)
public record Manager : Employee (managedEmployees: list[Employee])

_Records can only be instantiated with the required data_
record Message(text: string)
<b>OK</b> - def a = Message("Hello World")
<b>NOT OK</b> - def b = Message()

_Records can be sealed, meaning they will be generated as a struct vs. class during compile phase_
public sealed record Coordinate(x: int, y: int) // <--- Coordinate is a "struct" in the IL, not a class.

<hr />
I've already got a preliminary implementation of this feature, but I wanted to get the project collaborators thoughts before I submit a pull request.

What do you think?

**Comment by someone-with-default-username** [comment]
What is the problem you are solving with this new syntax?
Today in Nemerle [Record] macro is mostly used to autogenerate constructor for class/struct.

**Comment by NN---** [comment]
It is easy to write small macros.
See: 
https://github.com/NemerleWeb/NemerleWeb/blob/master/NemerleWeb.Macros/Data/Dto.n
https://github.com/NemerleWeb/NemerleWeb/blob/master/NemerleWeb.Macros/Data/Rec.n

The usage:

```
[Dto] class Task { Name : string; IsDone : bool } 
[Rec] class TaskImmutable { Name : string; IsDone : bool } 

def t = Task("a", true);
a.Name = "Q";
def t2 = TaskImmutable("b", false);
```

**Comment by antagonist112358** [comment]
Yeah, you could even put in the equality / gethashcode stuff in via a macro.

I don't have a specific use case, as this is a new feature. I think the pattern is useful enough, especially with pattern matching, to be promoted to a language level. I'm thinking variants come very close, but they don't allow for inheritance.

Use cases I see immediately are:
  - data types, types that only store data
  - pattern matching
  - ado.net / mapping objects
  - message passing data objects

All those implementations could be done with a combination of [Record] and Variant, I realize that. So finally it would be nice to have a clean, terse syntax for this frequently used pattern.

The idea comes from: http://www.scala-lang.org/old/node/107.html,  and http://en.m.wikipedia.org/wiki/Record_(computer_science)

**Comment by NN---** [comment]
You cannot make GetHashCode for mutable structures :)

Variants are closed set of immutable data types , this why you can make pattern matching and be sure nothing won't break.

You have sort of pattern matching for classes:

```nemerle
using System;

[Record] class A { public I : int; public J : string; }

public class Test
{
	public static Main() : void
	{
		def a = A(1, "A");
		match(a)
		{
		| A where (I = 1, J = "A") => Console.WriteLine("Matched"); // Syntax with 'where' is supported as well.
		| _ => Console.WriteLine("Not matched");
		}
	}
}
```

**Comment by antagonist112358** [comment]
You cannot make GetHashCode for mutable structures :)
  | Sure you can - its done all over the place in the .NET framework itself. As far as I know, its really only used for equality and Hashtables

I was doing some experimentation today, and it looks like [Record] class does appear to do everything that I was asking for <b>except</b> automatically create equality methods.

From this:
 
 [Record] public sealed class RecordExample {
      public Name : String;
      public Reference: Object;
  }

      public DoExtractMatch(r : RecordExample) : bool {
          | RecordExample("Hello World", null) => true
          | RecordExample("Hello World", r) when r != null => true
          | RecordExample(name, null) => name != null && name.Length == "Hello World".Length
      }

I got this out of RedGate Reflector:

public bool DoExtractMatch(RecordExample r)
{
    // This item is obfuscated and can not be translated.
    string name;
    RecordExample example = r;
    if (example.Name == "Hello World")
    {
        if (example.Reference != null)
        {
            if (example.Reference == null)
            {
                throw new MatchFailureException();
            }
        }
    }
    else
    {
        if (example.Reference != null)
        {
            throw new MatchFailureException();
        }
        name = example.Name;
    }
    return ((name != null) && (name.Length == "Hello World".Length));
}

Which is pretty impressive. It looks like match extraction without where is totally supported. Is this an optimization for classes with the [Record] attribute only?

**Comment by NN---** [comment]
There are macros GetHashCode and StructualEquality. I hope I didn't miss the correct name.
You can find them in the compiler's code.
The macro makes GetHashCode and operator== just as you expect.

As for the pattern arching I am not sure about special treating of Recorf but you don't need it ,you can always match using properties as I wrote.

**Comment by antagonist112358** [comment]
Yeah I just wrote a 4 line macro which adds in the [Record] and [StructuralEquality] macro attributes into a class using the keyword (lowercase) 'record'.

I'd say that although I'd like that to be included in the trunk, it is pretty duplicate of existing features.

As such, I'm marking this issue "closed".
