### ISSUE TITLE
Cannot build via DevBuildQuick-VS2015.cmd

### ISSUE THREAD

**Issue by vasily-kirichenko** [rsdn/nemerle#13307]
Windows 10 x64, VS 2015 Update 1. 
Also Windows SDK 8.1 has been installed in an attempt to fix the error:

![image](https://cloud.githubusercontent.com/assets/873919/12372314/c648ca16-bc62-11e5-95a7-26e6e8c60899.png)

Error:
```
Build FAILED.

"D:\github\nemerle\NemerleAll.nproj" (DevBuildQuick target) (1) ->
"D:\github\nemerle\Nemerle.nproj" (Build target) (3) ->
(AfterBuild target) -> 
  D:\github\nemerle\Nemerle.nproj(64,5): error MSB6004: The specified task executable location "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\AL.exe" is invalid.

    0 Warning(s)
    1 Error(s)
```
Full log:
```
> DevBuildQuick-VS2015.cmd

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m set MSBuild="C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" 

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m set NoPause=true 

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" NemerleAll.nproj /target:DevBuildQuick /p:Configuration=Debug /verbosity:n /p:NTargetName=Build  /tv:14.0 /p:TargetFrameworkVersion=v4.0 
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 16.01.2016 15:02:53.
Project "D:\github\nemerle\NemerleAll.nproj" on node 1 (DevBuildQuick target(s)).
NPrepareKeys:
  Copying file from "D:\github\nemerle\misc\keys\Nemerle.Compiler.snk" to "D:\github\nemerle\bin\Debug\net-4.0\keys\Nemerle.Compiler.snk".
  Copying file from "D:\github\nemerle\misc\keys\Nemerle.Evaluation.snk" to "D:\github\nemerle\bin\Debug\net-4.0\keys\Nemerle.Evaluation.snk".
  Copying file from "D:\github\nemerle\misc\keys\Nemerle.snk" to "D:\github\nemerle\bin\Debug\net-4.0\keys\Nemerle.snk".
NPrepareBoot:
  Copying file from "D:\github\nemerle\boot-4.0\\ncc.exe" to "D:\github\nemerle\bin\Debug\net-4.0\boot\ncc.exe".
  Copying file from "D:\github\nemerle\boot-4.0\\ncc32.exe" to "D:\github\nemerle\bin\Debug\net-4.0\boot\ncc32.exe".
  Copying file from "D:\github\nemerle\boot-4.0\\ncc64.exe" to "D:\github\nemerle\bin\Debug\net-4.0\boot\ncc64.exe".
  Copying file from "D:\github\nemerle\boot-4.0\\Nemerle.Compiler.dll" to "D:\github\nemerle\bin\Debug\net-4.0\boot\Nemerle.Compiler.dll".
  Copying file from "D:\github\nemerle\boot-4.0\\Nemerle.dll" to "D:\github\nemerle\bin\Debug\net-4.0\boot\Nemerle.dll".
  Copying file from "D:\github\nemerle\boot-4.0\\Nemerle.Macros.dll" to "D:\github\nemerle\bin\Debug\net-4.0\boot\Nemerle.Macros.dll".
InitTools:
  Framework tools found at:
       MSBuild  - C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
       NGen     - "C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe"
    SDK tools found at:
       GacUtil  - "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\gacutil.exe"
       Ildasm   - "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\ildasm.exe"
       PEVerify - "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\peverify.exe"
       ALPath   - 
    ExternalDependences:
       Junction - D:\github\nemerle\ExternalDependences\junction.exe
Project "D:\github\nemerle\NemerleAll.nproj" (1) is building "D:\github\nemerle\Nemerle.MSBuild.Tasks.csproj" (2) on node 1 (Build target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Nemerle.MSBuild.Tasks -> D:\github\nemerle\bin\Debug\net-4.0\boot\Nemerle.MSBuild.Tasks.dll
AfterBuild:
  Copying file from "D:\github\nemerle\\tools\msbuild-task\Nemerle.MSBuild.targets" to "D:\github\nemerle\bin\Debug\net-4.0\boot\Nemerle.MSBuild.targets".
Done Building Project "D:\github\nemerle\Nemerle.MSBuild.Tasks.csproj" (Build target(s)).
Project "D:\github\nemerle\NemerleAll.nproj" (1) is building "D:\github\nemerle\Nemerle.nproj" (3) on node 1 (Build target(s)).
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Nemerle -> D:\github\nemerle\bin\Debug\net-4.0\Stage1\Nemerle.dll
AfterBuild:
  Template replaced and written to 'D:\github\nemerle\bin\Debug\net-4.0\Stage1\policy.1.2.Nemerle.config'
D:\github\nemerle\Nemerle.nproj(64,5): error MSB6004: The specified task executable location "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\AL.exe" is invalid.
Done Building Project "D:\github\nemerle\Nemerle.nproj" (Build target(s)) -- FAILED.
Done Building Project "D:\github\nemerle\NemerleAll.nproj" (DevBuildQuick target(s)) -- FAILED.

Build FAILED.

"D:\github\nemerle\NemerleAll.nproj" (DevBuildQuick target) (1) ->
"D:\github\nemerle\Nemerle.nproj" (Build target) (3) ->
(AfterBuild target) -> 
  D:\github\nemerle\Nemerle.nproj(64,5): error MSB6004: The specified task executable location "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools\AL.exe" is invalid.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.15

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m rem /verbosity:n /p:TargetName=Build 

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m IF 1 == 0 call Reg-bins-VS2015.cmd 

[32m]9;8;"USERNAME"\@]9;8;"COMPUTERNAME"\ [92mD:\github\nemerle[90m
[90m>[m pause
```

**Comment by NN---** [comment]
Try to change NemerleAll.nproj from

```xml
      <Output Condition="'$(TargetFrameworkVersion)' == 'v4.0' Or '$(TargetFrameworkVersion)' == 'v4.5' Or '$(TargetFrameworkVersion)' == 'v4.5.1'" TaskParameter="Path" PropertyName="SDK_3" />
```

to 
```xml
      <Output Condition="'$(TargetFrameworkVersion)' == 'v4.0' Or '$(TargetFrameworkVersion)' == 'v4.5' Or '$(TargetFrameworkVersion)' == 'v4.5.1'" TaskParameter="FrameworkSdkVersion40Path" PropertyName="SDK_3" />
```

This should return a correct .NET 4.0 SDK

See https://msdn.microsoft.com/en-us/library/ms164298.aspx

**Comment by vasily-kirichenko** [comment]
It's not helped :(

However, DevBuildQuick.cmd has completed with no errors.

**Comment by NN---** [comment]
Which SDK path it returns ?
Typically SDK 7.0A contains .NET 4.0 tools.

I think you didn't choose it in the installation.
Reinstall it choosing .NET 4.0 tools.

**Comment by vasily-kirichenko** [comment]
I chose everything. OK, reinstall it.

BTW, what is the normal process of developing the VS integration? Is it:

* make a change
* BuildInstallerFast-4.cmd
* Run the installer
* Launch a VS instance
* Check the results

?

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/12376744/e74cac16-bd14-11e5-88a7-896de3016456.png)

Maybe it's a wrong SDK?

**Comment by NN---** [comment]
The build chooses SDK 7.0A   
Microsoft SDKs\Windows\v7.0A

It is Windows 7 and .NET 4.0 SDK.
Check that you have the folder: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\NETFX 4.0 Tools\

**Comment by NN---** [comment]
Normally you use DevBuild then it is easier to debug.
BuildInstaller builds Release.

If you want debug installer you  can use 


%MSBuild% NemerleAll.nproj /t:InstallerFull /tv:4.0 /p:TargetFrameworkVersion=v4.0;Configuration=**Debug**

**Comment by vasily-kirichenko** [comment]
The folder does not exists:

![image](https://cloud.githubusercontent.com/assets/873919/12376762/92f0108a-bd15-11e5-9005-7008f26aeca7.png)

**Comment by NN---** [comment]
Reinstall Microsoft Windows SDK for Windows 7 and .NET Framework 4

**Comment by vasily-kirichenko** [comment]
I tried and it fail. It said it requires .net framework 4.0. I tried to install it and windows said that it's already a part of the OS. It seems there's no way to install v.7.0A on win 10 :(

**Comment by NN---** [comment]
oh you have windows 10.
Then you must install VS2010 in order to get it correctly :)

**Comment by vasily-kirichenko** [comment]
wow :)

**Comment by NN---** [comment]
There are some hacks for installing SDK 7.0 for Windows 10 .
Other solution is to change current SDK version in the registry.

**Comment by NN---** [comment]
Check

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\ 
CurrentVersion


You have for HKEY_CURRENT_USER and 64bit of course depending what MSBuild takes.

**Comment by vasily-kirichenko** [comment]
The key contains 8.0.50727

**Comment by vasily-kirichenko** [comment]
OK, I'm installing VS 2010. Will see if it fixes the issue.

**Comment by vasily-kirichenko** [comment]
DevBuildQuick-VS2015.cmd built without errors :)

Then I uninstalled Nemerle from "add or remove apps" windows tool, then run the VSIX from d:\github\nemerle\bin\Debug\net-4.0\VsIntegration\Nemerle.VisualStudio.vsix and now no Nemerle projects can be loaded in VS 2015:

![image](https://cloud.githubusercontent.com/assets/873919/12376925/fa252244-bd1b-11e5-9b25-98e452b8afb2.png)

**Comment by NN---** [comment]
you should use msi and not vsix
bin\Debug\net-4.0\Installer

**Comment by NN---** [comment]
ah sorry , you want the devbuild

**Comment by NN---** [comment]
First check if you have Nemerle environment variable. If you have remove it.
Then install Nemerle and try devbuild
To run Nemerle in dev environment use 

You need something like
devenv.exe /rootsuffix Exp

**Comment by NN---** [comment]
Closing the issue.
This discussion should continue either in the forum rsdn.ru/forum/nemerle or in chat: https://gitter.im/rsdn/nemerle

**Comment by VladD2** [comment]
DevBuildQuick-VS2015.cmd - works well. No VS SDK need to install.

You have problems with the installation of the VS2015. Mybe are you've installed the older version of the VS after installing newer. Also mybe you remove the old version of VS after.

Simply copy exists "C:\Program Files (x86)\Microsoft SDKs\Windows\vXXX\\bin\NETFX XXX Tools" into "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\\bin\NETFX 4.0 Tools", or reinstall .Net Framworck in correct order (At first the old, then the new).

PS

This is Microsoft bug.

**Comment by VladD2** [comment]
Maybe have no .Net Framework 4.0. If you try to anstall it, do not forget to recover .Net 4.6 after.

**Comment by NN---** [comment]
Windows 10 has .NET 4.0 built-in

**Comment by VladD2** [comment]
I add some hack. Please, try build Nemerle on your computer.

**Comment by VladD2** [comment]
> Windows 10 has .NET 4.0 built-in

Sorre. I spoke about .Net SDK which install with VS.

**Comment by vasily-kirichenko** [comment]
It's built ok (via DevBuildQuick-VS2015.cmd)

When I try to compile a project, I get:

```
C:\Program Files (x86)\Nemerle\Net-4.0\Nemerle.MSBuild.targets(289,5): error : Could not load file or assembly 'Nemerle, Version=1.2.0.486, Culture=neutral, PublicKeyToken=e080a9c724e2bfcd' or one of its dependencies. The system cannot find the file specified.
Build has been canceled.
```

**Comment by VladD2** [comment]
Эта ситуация возникает, если перед установкой новой версии ВС удалить старую или поставить более старый дотнет фреймворк. Это может вызвать удаление или переписывание значения ключа HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows в котором указываетс путь к .Net SDK.
Чтобы исправить ситуацию нужно пропатчить реестр следующим скриптом:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows]
"CurrentInstallFolder"="c:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\"
```
где нужно прописать путь к .Net SDK
