### ISSUE TITLE
VS Plugin doesn't return the BuildAction property through IVsHierarchy

### ISSUE THREAD

**Issue by ssrmm** [rsdn/nemerle#13329]
The `out` parameter of the [IVsHierarchy.GetProperty](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivshierarchy.getproperty.aspx) method is `null` and a negative status is returned. This prevents the Nitra plugins from working in Nemerle projects because of the call in [VsUtils.cs#L47](https://github.com/rsdn/nitra/blob/e6ec92bbab5ac7521aea15565ba6741a2f7eb503/Ide/NitraCommonVSIX/Utils/VsUtils.cs#L47)

![1_changed](https://cloud.githubusercontent.com/assets/22149188/21386808/ed5d0540-c774-11e6-8363-282e73ba2468.png)
![2_changed](https://cloud.githubusercontent.com/assets/22149188/21386821/f2cbb634-c774-11e6-8618-1a951782e96b.png)

**Comment by VladD2** [comment]
Fixed.
