### ISSUE TITLE
References of Nemerle project not accessible for Nitra Plugin

### ISSUE THREAD

**Issue by ssrmm** [rsdn/nemerle#13333]
When working with Nemerle Projects the Nitra Plugin only loads the [hardcoded `mscorlib.dll`](https://github.com/rsdn/nitra/blob/c37367cca1e091b758ea35f2ff9e3046ef0ba287/Ide/NitraCommonVSIX/NitraCommonVsPackage.cs#L265-L266) and non of the other references. This can be seen in the output of the server cmd.

Here is a quick verification example:
```C#
using System.Xml; // Unresolved referene 'Xml'

namespace Test
{
    public class TestStreamProvider : IHasXmlNode // Unresolved referene 'IHasXmlNode'
    {
        public XmlNode GetNode() // Unresolved referene 'XmlNode'
        {
            throw new System.NotImplementedException();
        }
    }
}
```
In a Nemerle project this produces the three errors indicated by the comments, in a C# project it doesn't. Note that both projects do have a working reference to `System.Xml.dll`. So there shouldn't be any errors.

I haven't looked into this any deeper, so it might also be a Nitra issue. The fact that this is specific to Nemerle projects led my to the decision to post it here. If necessary it can still be "moved over" to the Nitra repository

**Comment by VladD2** [comment]
Fixed
